#!/usr/bin/bash

PUT(){ echo -en "\033[${1};${2}H";}
HIDCRSR(){ echo -en "\033[?25l";}
NORM(){ echo -en "\033[?12l\033[?25h";}

printf "\e[0;1;48;2;41;121;255m  [!] Enter new Username :                "
PUT 21 28
read user
printf "\e[1;30;48;2;0;230;118m  [!] Enter new Password :                "
PUT 22 28
read check
printf "\e[0;1;48;2;200;0;0m  [!] Re-Enter Password  :                "
getPassword() {
unset pass
while IFS= read -p "$prompt" -r -s -n 1 char
do
    if [[ $char == $'\0' ]] ; then
        break
    fi
    if [[ $char == $'\177' ]] ; then
        prompt=$'\b \b'
        pass="${pass%?}"
    else
        prompt='*'
        pass+="$char"
    fi
done
}
PUT 23 28
getPassword
if [[ $check = "$pass" ]];then
echo;echo -e "\e[0;1;30;48;2;200;255;255m  [√] Your M-Password As :                \e[0m "
HIDCRSR
PUT 24 28
echo -e "\e[0;1;30;48;2;200;255;255m$pass\e[0m"
echo -e "\e[0;1;48;2;200;0;0m  [!]                                     "
PUT 25 7
echo -e "\e[0;1;48;2;200;0;0mPlease Remember that all things !" | pv -qL 20
echo -e "\e[0;1;48;2;41;121;255m  [!]                                     "
PUT 26 7
echo -e '\e[0;1;48;2;41;121;255mOpen a new Session to see changes...\e[0m' | pv -qL 20;echo;NORM
else echo;echo -e "\e[0;1;38;2;200;0;0mPassword not matching...\e[0m";echo ;fi

cd /data/data/com.termux/files/home/login-page/temp

echo "spin () {" > login.enc
echo 'local pid=$!' >> login.enc
echo "local delay=0.05" >> login.enc
echo "local spinner=( '⠋' '⠙' '⠹' '⠼' '⠴' '⠦' '⠧' '⠇' '⠏' )" >> login.enc
echo 'while [ "$(ps a | awk '"'{print "'$1'"}'"' | grep $pid)" ]; do' >> login.enc
echo 'for i in "${spinner[@]}"' >> login.enc
echo "do" >> login.enc
echo "        HIDCRSR" >> login.enc
echo '        echo -ne "\e[0;1;48;2;41;121;255m\r   [!] Checking Input...\e[0;1;90;48;2;0;230;118m      [ $i ]       \033[3m\033[0m   ";' >> login.enc
echo '        sleep $delay' >> login.enc
echo '        printf "\b\b\b\b\b\b";' >> login.enc
echo "done" >> login.enc
echo "done" >> login.enc
echo 'printf "\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b"' >> login.enc
echo 'if [[ $1 == granted ]]; then' >> login.enc
echo 'printf "\e[0;1;48;2;41;121;255m\e[0;1;90;48;2;0;230;118m [ACCSES GRANTED] \e[0m\n"' >> login.enc
echo 'echo"";' >> login.enc
echo "NORM" >> login.enc
echo 'elif [[ $1 == denied ]]; then' >> login.enc
echo 'printf "\e[0;1;48;2;41;121;255m\e[0;1;48;2;200;0;0m [ACCESS DENIED]  \e[0m\n"' >> login.enc
echo "fi" >> login.enc
echo "}" >> login.enc
echo"" >> login.enc
echo"" >> login.enc
echo "getPassword() {" >> login.enc
echo "unset password" >> login.enc
echo 'while IFS= read -p "$prompt" -r -s -n 1 char' >> login.enc
echo "do" >> login.enc
echo '    if [[ $char == $'"'\0'"' ]] ; then' >> login.enc
echo "        break" >> login.enc
echo "    fi" >> login.enc
echo '    if [[ $char == $'"'\177'"' ]] ; then' >> login.enc
echo "        prompt=$'\b \b'" >> login.enc
echo '        password="${password%?}"' >> login.enc
echo "    else" >> login.enc
echo "        prompt='*'" >> login.enc
echo '        password+="$char"' >> login.enc
echo "    fi" >> login.enc
echo "done" >> login.enc
echo "}" >> login.enc
echo"" >> login.enc
echo 'PUT(){ echo -en "\033[${1};${2}H";}' >> login.enc
echo 'HIDCRSR(){ echo -en "\033[?25l";}' >> login.enc
echo 'NORM(){ echo -en "\033[?12l\033[?25h";}' >> login.enc
echo"" >> login.enc
echo "bash /data/data/com.termux/files/home/login-page/header/header.ui" >> login.enc
echo "trap '' 2" >> login.enc
echo "bash /data/data/com.termux/files/home/login-page/header/header.option" >> login.enc
echo "PUT 10 26" >> login.enc
echo 'printf "\e[0m'$user'\e[1;m" | pv -qL 20' >> login.enc
echo "PUT 11 26" >> login.enc
echo "getPassword" >> login.enc
echo"" >> login.enc
echo 'if [[ $password = "'$pass'" ]];then' >> login.enc
echo 'echo"";' >> login.enc
echo 'echo"";' >> login.enc
echo "(sleep 1) &> /dev/null & spin granted" >> login.enc
echo "trap 5" >> login.enc
echo"" >> login.enc
echo "else" >> login.enc
echo "trap '' 2" >> login.enc
echo 'echo"";' >> login.enc
echo 'echo"";' >> login.enc
echo '(sleep 1) &> /dev/null & spin denied ; printf "\e[1;91m" ; kill -9 $PPID' >> login.enc
echo "fi" >> login.enc
echo "trap 5" >> login.enc
chmod +x login.enc
