#!/usr/bin/bash

PUT(){ echo -en "\033[${1};${2}H";}
HIDCRSR(){ echo -en "\033[?25l";}
NORM(){ echo -en "\033[?12l\033[?25h";}

export CREDS="$PREFIX/etc/login-config/creds.login"

C0="$(printf '\033[90m')"
C1="$(printf '\033[91m')"
C2="$(printf '\033[92m')"
C3="$(printf '\033[93m')"
C4="$(printf '\033[94m')"
C5="$(printf '\033[95m')"
C6="$(printf '\033[96m')"
C7="$(printf '\033[97m')"
R0="$(printf '\033[00m')"
R1="$(printf '\033[01m')"
R2="$(printf '\033[02m')"
R3="$(printf '\033[03m')"
R4="$(printf '\033[04m')"

OP()
{
printf "${C2}(${R0}$1${C2})${R0}"
}

printf "  $(OP '>') Enter new username of login : "
read user
printf "  $(OP '>') Enter new password of login : "
read check
printf "  $(OP '>') Enter again password of login : "
getPassword() {
unset pass
while IFS= read -p "$prompt" -r -s -n 1 char
do
    if [[ $char == $'\0' ]] ; then
        break
    fi
    if [[ $char == $'\177' ]] ; then
        prompt=$'\b \b'
        pass="${pass%?}"
    else
        prompt='*'
        pass+="$char"
    fi
done
}
getPassword
if [[ $check = "$pass" ]];then
echo -e "\n  (-) Your Master Password is : $pass\e[0m "
echo -e '  (-) Now open new session to see changes.\e[0m'
else echo -e "\n  (!) Password doesn't match, enter setup again.\e[0m"
exit 1
fi

pass=$(printf "$pass" | sha256sum | awk '{print $1}')

cd /data/data/com.termux/files/home/Login-Page/temp

echo 'if [ -f "/data/data/com.termux/files/usr/tmp/anim.success" ];then cat /data/data/com.termux/files/usr/etc/login-config/motd.login ;exit' > login.enc
echo "else" >> login.enc
echo "main() {" >> login.enc
echo "spin () {" >> login.enc
echo 'local pid=$!' >> login.enc
echo "local delay=0.05" >> login.enc
echo "local spinner=( '⠋' '⠙' '⠹' '⠼' '⠴' '⠦' '⠧' '⠇' '⠏' )" >> login.enc
echo 'while [ "$(ps a | awk '"'{print "'$1'"}'"' | grep $pid)" ]; do' >> login.enc
echo 'for i in "${spinner[@]}"' >> login.enc
echo "do" >> login.enc
echo "        HIDCRSR" >> login.enc
echo '        echo -ne "\e[0;1;48;2;41;121;255m\r  [!] Checking Input... \e[0;1;90;48;2;0;230;118m      [ $i ]       \033[3m\033[0m   ";' >> login.enc
echo '        sleep $delay' >> login.enc
echo '        printf "\b\b\b\b\b\b";' >> login.enc
echo "done" >> login.enc
echo "done" >> login.enc
echo 'printf "\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b"' >> login.enc
echo 'if [[ $1 == granted ]]; then' >> login.enc
echo 'printf "\e[0;1;48;2;41;121;255m\e[0;1;90;48;2;0;230;118m [ACCSES GRANTED] \e[0m\n"' >> login.enc
echo 'echo"";' >> login.enc
echo "NORM" >> login.enc
echo 'elif [[ $1 == denied ]]; then' >> login.enc
echo 'printf "\e[0;1;48;2;41;121;255m\e[0;1;48;2;200;0;0m [ACCESS DENIED]  \e[0m\n"' >> login.enc
echo "fi" >> login.enc
echo "}" >> login.enc
echo"" >> login.enc
echo"" >> login.enc
echo "getPassword() {" >> login.enc
echo "unset password" >> login.enc
echo 'while IFS= read -p "$prompt" -r -s -n 1 char' >> login.enc
echo "do" >> login.enc
echo '    if [[ $char == $'"'\0'"' ]] ; then' >> login.enc
echo "        break" >> login.enc
echo "    fi" >> login.enc
echo '    if [[ $char == $'"'\177'"' ]] ; then' >> login.enc
echo "        prompt=$'\b \b'" >> login.enc
echo '        password="${password%?}"' >> login.enc
echo "    else" >> login.enc
echo "        prompt='*'" >> login.enc
echo '        password+="$char"' >> login.enc
echo "    fi" >> login.enc
echo "done" >> login.enc
echo "}" >> login.enc
echo"" >> login.enc
echo 'PUT(){ echo -en "\033[${1};${2}H";}' >> login.enc
echo 'HIDCRSR(){ echo -en "\033[?25l";}' >> login.enc
echo 'NORM(){ echo -en "\033[?12l\033[?25h";}' >> login.enc
echo"" >> login.enc
echo "bash /data/data/com.termux/files/usr/etc/login-config/header/header.ui" >> login.enc
echo "trap '' 2" >> login.enc
echo "bash /data/data/com.termux/files/usr/etc/login-config/header/header.option" >> login.enc
echo "PUT 11 24" >> login.enc
echo 'printf "\e[1;48;2;41;121;255m                "' >> login.enc
echo "PUT 10 24" >> login.enc
echo 'printf "\e[1;90;48;2;0;230;118m                "' >> login.enc
echo "PUT 10 24" >> login.enc
echo 'printf "\e[1;90;48;2;0;230;118m'$user'\e[0;1m" | pv -qL 20' >> login.enc
echo "PUT 11 24" >> login.enc
echo 'printf "\e[1;48;2;41;121;255m"' >> login.enc
echo "getPassword" >> login.enc
echo "PASSWD() {" >> login.enc
echo "printf "'$password'" | sha256sum | awk '{print \$1}'" >> login.enc
echo "}" >> login.enc
echo"" >> login.enc
echo 'if [[ $(PASSWD) = "'$pass'" ]];then' >> login.enc
echo 'echo"";' >> login.enc
echo 'echo"";' >> login.enc
echo "(sleep 1) &> /dev/null & spin granted" >> login.enc
echo "cd /data/data/com.termux/files/usr/tmp ; touch anim.success ; cd $HOME" >> login.enc
echo "trap 5" >> login.enc
echo"" >> login.enc
echo "else" >> login.enc
echo "trap '' 2" >> login.enc
echo 'echo"";' >> login.enc
echo 'echo"";' >> login.enc
echo '(sleep 1) &> /dev/null & spin denied ; printf "\e[1;91m" ; kill -9 $PPID' >> login.enc
echo "fi" >> login.enc
echo "trap 5" >> login.enc
echo 'if [ -f "/data/data/com.termux/files/usr/etc/login-config/font/font.login" ];then cd /data/data/com.termux/files/usr/etc/login-config/font ; bash font.login ;fi ; } ;fi' >> login.enc
echo "trap '' SIGTSTP" >>login.enc
echo "trap '' SIGINT" >> login.enc
echo "main" >> login.enc
chmod +x login.enc
